### ISSUE TITLE
Common Component: kubeflow-roles

### ISSUE THREAD

**Issue by sylus** [StatCan/aaw-kubeflow-manifests#113]
## Overview

**EPIC**: [Kubeflow Upgrade Planning][epic-kubeflow]

| Component      | Local Manifests Path                          | Upstream | Initial Work |
| -------------- | --------------------------------------------- | -------- | ------------ |
| kubeflow-roles | [common/kubeflow-roles][local-kubeflow-roles] | `v1.3.1` |              |

[epic-kubeflow]: https://github.com/StatCan/aaw-kubeflow-manifests/issues/110
[local-kubeflow-roles]: https://github.com/StatCan/aaw-kubeflow-manifests/tree/main/kustomize/common/kubeflow-roles

## Kubeflow V2 Manifests

The following is the kustomize that was used in Kubeflow V2:

- https://github.com/StatCan/aaw-kubeflow-manifests/tree/master/kustomize/application/kubeflow-roles

```sh
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../../.cache/manifests/manifests-1.2-branch/kubeflow-roles/base
```

## AAW Dev / Prod Live Manifests

At the moment there is no difference in state then what is overridden above.

> **Note**: While most everything 95% would have been automated, stored as config and is using what is referenced above. I believe a few things could have been done as manual adjustments that we should make sure we are keeping. Largely any manual yaml adjustments would have been documented in high level GitHub issues or tracked in the YAML repository under the AAW group.

## Kubeflow V3 Manifests

The following is the P.R. that will be merged into the main branch for Kubeflow V3:

-  No PR is needed. Kubeflow-roles references upstream without any overrides. https://github.com/StatCan/aaw-kubeflow-manifests/tree/main/kustomize/common/kubeflow-roles

```sh
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- github.com/kubeflow/manifests/common/kubeflow-roles/base?ref=v1.3.1
```

## Testing

Usually a good idea to make sure all of the overrides are working is to run the following command and verify all of the yaml output for the component is what you expect and all of the overrides are taken into account.

- The kubeflow-roles upstream base folder manifest file cluster-roles.yaml was outputted.

```sh
task stack:aaw:preview
```

> **Note**: The command above will render all of the manifests into manifests top level folder with the name `aaw.yaml`. A trick to keep the yaml output small is under `stacks/aaw/kustomization.yaml` to only have the component you wish to test referenced.

**Comment by rohank07** [comment]
@sylus No PR is needed for this issue.  Already brought in the [manifest](https://github.com/StatCan/aaw-kubeflow-manifests/tree/main/kustomize/common/kubeflow-roles) file referencing upstream v1.3.1

**Comment by sylus** [comment]
Great thanks @rohank07 !
