### ISSUE TITLE
Contrib component: metacontroller

### ISSUE THREAD

**Issue by rohank07** [StatCan/aaw-kubeflow-manifests#120]
## Overview

**EPIC**: [Kubeflow Upgrade Planning][epic-kubeflow]

| Component        | Local Manifests Path                            | Upstream | Initial Work                         |
| ---------------- | ----------------------------------------------- | -------- | ------------------------------------ |
| metacontroller | [apps/metacontroller][local-metacontroller] | `v1.3.1` | |

[epic-kubeflow]: https://github.com/StatCan/aaw-kubeflow-manifests/issues/110
[local-metacontroller]: https://github.com/StatCan/aaw-kubeflow-manifests/tree/main/kustomize/contrib/metacontroller
[issue-aaw-argocd-manifests-35]: https://github.com/StatCan/aaw-argocd-manifests/pull/35

**Comment by rohank07** [comment]
I think we can close this. meta-controller is brought in by [pipelines](https://github.com/StatCan/aaw-kubeflow-manifests/blob/main/kustomize/apps/pipeline/base/kustomization.yaml#L21) and there are no custom overrides in v1.2 https://github.com/StatCan/aaw-kubeflow-manifests/blob/master/kustomize/metacontroller/kustomization.yaml

**Comment by sylus** [comment]
@rohank07 i think we still need to include:

https://github.com/kubeflow/manifests/tree/master/contrib/metacontroller/base ?

**Comment by sylus** [comment]
Hmm very odd your right and ok then I guess we good!

**Comment by rohank07** [comment]
Closing: Came to conclusion metacontroller is apart of pipeline's base.
