### ISSUE TITLE
Apps Component: profiles

### ISSUE THREAD

**Issue by rohank07** [StatCan/aaw-kubeflow-manifests#123]
## Overview

**EPIC**: [Kubeflow Upgrade Planning][epic-kubeflow]

| Component          | Local Manifests Path                                  | Upstream | Initial Work |
| ------------------ | ----------------------------------------------------- | -------- | ------------ |
| profiles | [apps/profiles][local-profiles]    | `v1.3.1` |              |

[epic-kubeflow]: https://github.com/StatCan/aaw-kubeflow-manifests/issues/110
[local-profiles]: https://github.com/StatCan/aaw-kubeflow-manifests/tree/main/kustomize/apps/profiles

## Adjustments

- Bring in imagePullSecrets, and kfam :latest image

## Kubeflow V2 Manifests

The following is the kustomize that was used in Kubeflow V2:

- https://github.com/StatCan/aaw-kubeflow-manifests/tree/master/kustomize/application/profiles

```sh
apiVersion: kustomize.config.k8s.io/v1beta1
images:
- name: gcr.io/kubeflow-images-public/kfam
  newName: k8scc01covidacr.azurecr.io/kfam
  newTag: latest
kind: Kustomization
namespace: kubeflow
patchesStrategicMerge:
- deployment.yaml
resources:
- ../../../.cache/manifests/manifests-1.2-branch/profiles/base_v3
```

## AAW Dev / Prod Live Manifests

At the moment there is no difference in state then what is overridden above.

> **Note**: While most everything 95% would have been automated, stored as config and is using what is referenced above. I believe a few things could have been done as manual adjustments that we should make sure we are keeping. Largely any manual yaml adjustments would have been documented in high level GitHub issues or tracked in the YAML repository under the AAW group.

## Kubeflow V3 Manifests

The following is the P.R. that will be merged into the main branch for Kubeflow V3:

- #141 

```sh
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kubeflow

resources:
- github.com/kubeflow/manifests/apps/profiles/upstream/overlays/kubeflow?ref=v1.3.1


patchesStrategicMerge:
- deployment.yaml

images:
- name: gcr.io/kubeflow-images-public/kfam
  newName: k8scc01covidacr.azurecr.io/kfam
  newTag: latest


```

## Testing

Usually a good idea to make sure all of the overrides are working is to run the following command and verify all of the yaml output for the component is what you expect and all of the overrides are taken into account.

- Deployment with imagePullSecrets ouputted successfully

```sh
task stack:aaw:preview
```

> **Note**: The command above will render all of the manifests into manifests top level folder with the name `aaw.yaml`. A trick to keep the yaml output small is under `stacks/aaw/kustomization.yaml` to only have the component you wish to test referenced.

**Comment by sylus** [comment]
Your P.R. doesn't seem to match what is says in the issue above?

The content of the deployment file looks off I think?

```sh
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
spec:
  template:
    spec:
      imagePullSecrets:
      - name: k8scc01covidacr-registry-connection
 ```

**Comment by rohank07** [comment]
My bad! I accidently copied v1.3 upstream kustomize file.
